"""Lead update migration

Revision ID: 0ec21941a859
Revises: cb71ada10c11
Create Date: 2025-09-29 22:49:43.084325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec21941a859'
down_revision = 'cb71ada10c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep lead_id nullable for existing data; enforce NOT NULL later after backfill
    # with op.batch_alter_table('customers', schema=None) as batch_op:
    #     batch_op.alter_column('lead_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenced_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('referenced_by')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
