"""Added mobileNo

Revision ID: 81a0ee186ca0
Revises: 0b13cae3b3c7
Create Date: 2025-09-12 16:37:04.337286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a0ee186ca0'
down_revision = '0b13cae3b3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobileNo', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['mobileNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mobileNo')

    # ### end Alembic commands ###
