"""Remove or comment out this line

Revision ID: b69397ae2a66
Revises: a81ba10a12d9
Create Date: 2025-09-30 15:19:48.628889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69397ae2a66'
down_revision = 'a81ba10a12d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('address_type')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_column('address_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
