"""Make business_id nullable in status_list

Revision ID: c596acdd4bae
Revises: ebefcbdf282d
Create Date: 2025-08-20 23:02:14.720047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c596acdd4bae'
down_revision = 'ebefcbdf282d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_list', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('status_list_business_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('status_list_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
