"""Updated Address model, made business_id nullable

Revision ID: c5c0960b9470
Revises: 8528bab71730
Create Date: 2025-09-01 18:58:49.070969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c0960b9470'
down_revision = '8528bab71730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('active',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('active_type_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('referenced_by', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['active_type_id'], ['active_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('businesses_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_constraint('item_categories_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint('item_images_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_constraint('item_types_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.drop_constraint('measuring_units_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('person_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('person_addresses_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('person_types', schema=None) as batch_op:
        batch_op.drop_constraint('person_types_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint('persons_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('persons_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('person_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('person_types_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('person_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('person_addresses_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('measuring_units_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('items_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('item_types_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('item_images_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('item_categories_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('businesses_address_id_fkey', 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('active')
    op.drop_table('active_types')
    # ### end Alembic commands ###
