"""Lead table migration

Revision ID: cb71ada10c11
Revises: a4f72a1c84f6
Create Date: 2025-09-29 22:34:23.462584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb71ada10c11'
down_revision = 'a4f72a1c84f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gst', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('shippings',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pin', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('lead_addresses',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('shipping_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_id'], ['shippings.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # Add address_type as nullable with a server default to backfill existing rows
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.Integer(), nullable=True, server_default='0'))
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # Ensure all existing rows have a value for address_type
    op.execute("UPDATE addresses SET address_type = 0 WHERE address_type IS NULL")

    # Now enforce NOT NULL and drop the server default if desired
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_type',
               existing_type=sa.Integer(),
               nullable=False,
               server_default=None)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint('customers_person_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['lead_id'])
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['uuid'], ondelete='CASCADE')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('customers_person_id_key', ['person_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('address_type')

    op.drop_table('lead_addresses')
    op.drop_table('shippings')
    op.drop_table('leads')
    # ### end Alembic commands ###
