"""Make business_id nullable

Revision ID: e1bf66ad4f0e
Revises: 5dc35df03744
Create Date: 2025-08-19 17:10:50.200654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bf66ad4f0e'
down_revision = '5dc35df03744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_types', schema=None) as batch_op:
        batch_op.drop_constraint('active_types_business_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('active_types_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
