"""Added FirstName, LastName

Revision ID: 0b13cae3b3c7
Revises: c5c0960b9470
Create Date: 2025-09-12 14:43:43.541709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b13cae3b3c7'
down_revision = 'c5c0960b9470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active', schema=None) as batch_op:
        batch_op.drop_constraint('active_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('addresses_business_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('businesses_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_constraint('item_categories_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint('item_images_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_constraint('item_types_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.drop_constraint('measuring_units_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('person_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('person_addresses_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('person_types', schema=None) as batch_op:
        batch_op.drop_constraint('person_types_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint('persons_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=80), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('lastName', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('persons_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('person_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('person_types_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('person_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('person_addresses_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('measuring_units_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('items_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('item_types_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('item_images_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('item_categories_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('businesses_address_id_fkey', 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('addresses_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('active', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('active_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
