"""Create invoice and invoice_items models

Revision ID: 1282b813c7d0
Revises: add_address_type_to_shippings
Create Date: 2026-02-03 20:43:01.595048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1282b813c7d0'
down_revision = 'add_address_type_to_shippings','2f004cbbc09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charges', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('additional_notes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('invoice_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.JSON(), nullable=True),
    sa.Column('tax', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('lead_addresses_shipping_id_fkey', type_='foreignkey')
        batch_op.drop_column('shipping_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.drop_constraint('quotation_items_measuring_unit_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('price_before_discount')
        batch_op.drop_column('terms_and_conditions')
        batch_op.drop_column('measuring_unit_id')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('notes')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('hsn_sac_code')
        batch_op.drop_column('tax_percentage')
        batch_op.drop_column('product_name')
        batch_op.drop_column('tax_amount')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('charges', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['quotation_number'])
        batch_op.drop_constraint('quotations_billing_address_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('quotations_shipping_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('discount_total')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('billing_address_id')
        batch_op.drop_column('tax_total')
        batch_op.drop_column('shipping_address_id')
        batch_op.drop_column('additional_charges_total')
        batch_op.drop_column('round_off')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint('shippings_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('shippings_address_id_fkey', 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_off', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('additional_charges_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shipping_address_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tax_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_address_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discount_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('quotations_shipping_address_id_fkey', 'addresses', ['shipping_address_id'], ['uuid'], ondelete='RESTRICT')
        batch_op.create_foreign_key('quotations_billing_address_id_fkey', 'addresses', ['billing_address_id'], ['uuid'], ondelete='RESTRICT')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('charges')
        batch_op.drop_column('quotation_number')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tax_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hsn_sac_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('measuring_unit_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('terms_and_conditions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_before_discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quotation_items_measuring_unit_id_fkey', 'measuring_units', ['measuring_unit_id'], ['id'])
        batch_op.drop_column('total_price')
        batch_op.drop_column('tax')
        batch_op.drop_column('discount')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('lead_addresses_shipping_id_fkey', 'shippings', ['shipping_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
