"""Added the quotation table

Revision ID: 1923cfb0ccbb
Revises: 27ab3962863c
Create Date: 2026-01-23 11:25:32.605684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1923cfb0ccbb'
down_revision = '27ab3962863c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('billing_address_id', sa.UUID(), nullable=False),
    sa.Column('shipping_address_id', sa.UUID(), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('additional_charges_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['addresses.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('quotation_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('measuring_unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_before_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['measuring_unit_id'], ['measuring_units.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('customer_addresses')
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_index('idx_shippings_address_id')
        batch_op.drop_index('idx_shippings_customer_id')

    op.drop_table('shippings')
    with op.batch_alter_table('active', schema=None) as batch_op:
        batch_op.drop_constraint('fk_active_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_active_updated_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('active_types', schema=None) as batch_op:
        batch_op.drop_constraint('fk_active_types_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_active_types_created_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('fk_addresses_customer', type_='foreignkey')
        batch_op.drop_constraint('fk_addresses_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_addresses_created_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_businesses_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_businesses_created_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_mobile_key', type_='unique')
        batch_op.create_unique_constraint('uq_customers_lead_id', ['lead_id'])

    # Get the primary key column of the users table
    pk_columns = op.get_bind().execute(
        sa.text("""
            SELECT column_name 
            FROM information_schema.table_constraints tc
            JOIN information_schema.constraint_column_usage AS ccu 
              ON ccu.constraint_name = tc.constraint_name
            WHERE tc.table_name = 'users' 
            AND tc.constraint_type = 'PRIMARY KEY';
        """)
    ).fetchone()
    
    pk_column = pk_columns[0] if pk_columns else 'id'  # default to 'id' if not found
    
    # --- CREATED_BY (INTEGER → UUID mapping) ---
    with op.batch_alter_table('item_categories') as batch_op:
        batch_op.add_column(
            sa.Column('created_by_uuid', sa.UUID(), nullable=True)
        )

    # Map the integer created_by to UUID using the users table
    op.execute(f"""
        UPDATE item_categories ic
        SET created_by_uuid = u.uuid
        FROM users u
        WHERE ic.created_by::text = u.{pk_column}::text
    """)

    # --- UPDATED_BY (INTEGER → UUID mapping) ---
    with op.batch_alter_table('item_categories') as batch_op:
        batch_op.add_column(
            sa.Column('updated_by_uuid', sa.UUID(), nullable=True)
        )

    # Map the integer updated_by to UUID using the users table
    op.execute(f"""
        UPDATE item_categories ic
        SET updated_by_uuid = u.uuid
        FROM users u
        WHERE ic.updated_by::text = u.{pk_column}::text
    """)

    # Drop the old columns and rename the new ones
    with op.batch_alter_table('item_categories') as batch_op:
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')
        batch_op.alter_column(
            'created_by_uuid',
            new_column_name='created_by'
        )
        batch_op.alter_column(
            'updated_by_uuid',
            new_column_name='updated_by'
        )

    # --- OTHER SAFE CHANGES ---
    with op.batch_alter_table('item_categories') as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP')
        )

       #  batch_op.create_unique_constraint(None, ['name'])

        batch_op.create_foreign_key(
            None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL'
        )

        batch_op.create_foreign_key(
            None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL'
        )

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('fk_item_images_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_item_images_created_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_types_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_item_types_updated_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')

    # Then handle items category_id NULL values
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT uuid::text FROM item_categories LIMIT 1")).fetchone()
    if result:
        category_uuid = result[0]
        # Use string formatting for the parameter
        conn.execute(sa.text(f"""
            UPDATE items 
            SET category_id = '{category_uuid}'::uuid
            WHERE category_id IS NULL
        """))
    
    # First drop the foreign key constraint in item_images that depends on uq_items_uuid_new
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_images_item_uuid_new', type_='foreignkey')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('gst_tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('ix_items_uuid_new')
        batch_op.drop_constraint('uq_items_uuid_new', type_='unique')
        # Only create unique constraint on item_code, not item_name
        batch_op.create_unique_constraint(None, ['item_code'])
        batch_op.drop_constraint('fk_items_category', type_='foreignkey')
        batch_op.drop_constraint('fk_items_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_items_updated_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'measuring_units', ['measuring_unit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'item_types', ['item_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'item_categories', ['category_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.drop_column('uuid')

    # FIX: Handle lead_addresses created_by and updated_by conversion from INTEGER to UUID
    # Add temporary UUID columns
    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_uuid', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_uuid', sa.UUID(), nullable=True))
    
    # Map integer values to UUID
    conn = op.get_bind()
    conn.execute(sa.text(f"""
        UPDATE lead_addresses la
        SET created_by_uuid = u.uuid
        FROM users u
        WHERE la.created_by::text = u.{pk_column}::text
    """))
    
    conn.execute(sa.text(f"""
        UPDATE lead_addresses la
        SET updated_by_uuid = u.uuid
        FROM users u
        WHERE la.updated_by::text = u.{pk_column}::text
    """))
    
    # Clean up orphaned records before creating foreign key constraints
    conn = op.get_bind()
    conn.execute(sa.text("""
        DELETE FROM lead_addresses 
        WHERE address_id NOT IN (SELECT uuid FROM addresses)
    """))
    
    # Drop old columns and rename new ones
    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')
        batch_op.alter_column('created_by_uuid', new_column_name='created_by')
        batch_op.alter_column('updated_by_uuid', new_column_name='updated_by')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        # Create foreign key with proper ondelete behavior
        batch_op.create_foreign_key('fk_lead_addresses_lead_id', 'leads', ['lead_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_lead_addresses_updated_by', 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_lead_addresses_address_id', 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_lead_addresses_created_by', 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.drop_column('shipping_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('gst',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('referenced_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('fk_leads_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_leads_updated_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.drop_constraint('fk_measuring_units_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_measuring_units_created_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('status_list', schema=None) as batch_op:
        batch_op.drop_constraint('fk_status_list_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_status_list_updated_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('user_business', schema=None) as batch_op:
        batch_op.drop_constraint('user_business_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['uuid'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendors_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_vendors_created_by_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_vendors_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_vendors_updated_by_users', 'users', ['updated_by'], ['uuid'])

    with op.batch_alter_table('user_business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_business_user_id_fkey', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('status_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_status_list_updated_by_users', 'users', ['updated_by'], ['uuid'])
        batch_op.create_foreign_key('fk_status_list_created_by_users', 'users', ['created_by'], ['uuid'])

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_measuring_units_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_measuring_units_updated_by_users', 'users', ['updated_by'], ['uuid'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_leads_updated_by_users', 'users', ['updated_by'], ['uuid'])
        batch_op.create_foreign_key('fk_leads_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('referenced_by',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gst',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_items_updated_by_users', 'users', ['updated_by'], ['uuid'])
        batch_op.create_foreign_key('fk_items_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_items_category', 'item_categories', ['category_id'], ['uuid'], ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('uq_items_uuid_new', ['id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('ix_items_uuid_new', ['id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('gst_tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_item_types_updated_by_users', 'users', ['updated_by'], ['uuid'])
        batch_op.create_foreign_key('fk_item_types_created_by_users', 'users', ['created_by'], ['uuid'])

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_item_images_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_item_images_updated_by_users', 'users', ['updated_by'], ['uuid'])
        batch_op.alter_column('item_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_lead_id', type_='unique')
        batch_op.create_unique_constraint('customers_mobile_key', ['mobile'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_businesses_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_businesses_updated_by_users', 'users', ['updated_by'], ['uuid'])

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_addresses_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_addresses_updated_by_users', 'users', ['updated_by'], ['uuid'])
        batch_op.create_foreign_key('fk_addresses_customer', 'customers', ['customer_id'], ['uuid'])
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('active_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_active_types_created_by_users', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_active_types_updated_by_users', 'users', ['updated_by'], ['uuid'])
    # ### end Alembic commands ###
