"""Add shipping_id to lead_addresses table

Revision ID: 199309751da1
Revises: f3ecc8d828d1
Create Date: 2026-01-23 13:34:22.450982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '199309751da1'
down_revision = 'f3ecc8d828d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_addresses')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_addresses_customer', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['item_name'])

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'shippings', ['shipping_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_shippings_address_id')
        batch_op.drop_index('idx_shippings_customer_id')
        batch_op.drop_constraint('fk_shippings_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_shippings_customer', type_='foreignkey')
        batch_op.drop_constraint('fk_shippings_address', type_='foreignkey')
        batch_op.drop_constraint('fk_shippings_created_by', type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_shippings_created_by', 'users', ['created_by'], ['uuid'])
        batch_op.create_foreign_key('fk_shippings_address', 'addresses', ['address_id'], ['uuid'])
        batch_op.create_foreign_key('fk_shippings_customer', 'customers', ['customer_id'], ['uuid'])
        batch_op.create_foreign_key('fk_shippings_updated_by', 'users', ['updated_by'], ['uuid'])
        batch_op.create_index('idx_shippings_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_shippings_address_id', ['address_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('address_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipping_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_addresses_customer', 'customers', ['customer_id'], ['uuid'])

    op.create_table('customer_addresses',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], name='fk_customer_addresses_address'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], name='fk_customer_addresses_customer'),
    sa.PrimaryKeyConstraint('uuid', name='customer_addresses_pkey')
    )
    # ### end Alembic commands ###
