"""invoice

Revision ID: 20a7dd1f1a10
Revises: b1e2f3a4c5d6
Create Date: 2026-03-06 17:03:11.055055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a7dd1f1a10'
down_revision = 'b1e2f3a4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charges', sa.JSON(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('additional_notes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('invoice_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.JSON(), nullable=True),
    sa.Column('tax', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('idx_customers_active', postgresql_where='(is_deleted = false)')
        batch_op.drop_index('idx_customers_fullname_trgm', postgresql_ops={"lower((first_name::text || ' '::text) || last_name::text)": 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(is_deleted = false)')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_item_code_key', type_='unique')
        batch_op.drop_constraint('items_item_name_key', type_='unique')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_lead_addresses_address_id')
        batch_op.drop_index('idx_lead_addresses_lead_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('idx_leads_active_created', postgresql_where='(is_deleted = false)')
        batch_op.drop_index('idx_leads_active_status_created', postgresql_where='(is_deleted = false)')
        batch_op.drop_index('idx_leads_fullname_trgm', postgresql_ops={"lower((first_name::text || ' '::text) || last_name::text)": 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(is_deleted = false)')

    with op.batch_alter_table('payment_ins', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_index('idx_shippings_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.create_index('idx_shippings_customer_id', ['customer_id'], unique=False)

    with op.batch_alter_table('payment_ins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('idx_leads_fullname_trgm', [sa.text("lower((first_name::text || ' '::text) || last_name::text)")], unique=False, postgresql_ops={"lower((first_name::text || ' '::text) || last_name::text)": 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(is_deleted = false)')
        batch_op.create_index('idx_leads_active_status_created', ['status', 'created_at'], unique=False, postgresql_where='(is_deleted = false)')
        batch_op.create_index('idx_leads_active_created', ['created_at'], unique=False, postgresql_where='(is_deleted = false)')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.create_index('idx_lead_addresses_lead_id', ['lead_id'], unique=False)
        batch_op.create_index('idx_lead_addresses_address_id', ['address_id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint('items_item_name_key', ['item_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('items_item_code_key', ['item_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customers_fullname_trgm', [sa.text("lower((first_name::text || ' '::text) || last_name::text)")], unique=False, postgresql_ops={"lower((first_name::text || ' '::text) || last_name::text)": 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(is_deleted = false)')
        batch_op.create_index('idx_customers_active', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')

    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
