"""Added gst colum

Revision ID: 229093393cf3
Revises: c8dcb900d93e
Create Date: 2025-08-20 20:35:19.613356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229093393cf3'
down_revision = 'c8dcb900d93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('persons'):
        with op.batch_alter_table('persons', schema=None) as batch_op:
            batch_op.add_column(sa.Column('gst', sa.String(length=20), nullable=True))
            # Check if column 'test' exists before dropping
            columns = [c['name'] for c in inspector.get_columns('persons')]
            if 'test' in columns:
                batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('gst')

    # ### end Alembic commands ###
