"""Add isUT flag to users table

Revision ID: 234dafe8acf5
Revises: 3b95e5626f16
Create Date: 2026-02-20 16:39:56.384156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234dafe8acf5'
down_revision = '3b95e5626f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isUT', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isUT')

    # ### end Alembic commands ###
