"""Removed the status from the invoice table

Revision ID: 260b178d687c
Revises: 94ad88c164eb
Create Date: 2026-02-19 19:44:16.542423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260b178d687c'
down_revision = '94ad88c164eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
