"""added reson colum

Revision ID: 2ae3abb66486
Revises: 60c5034e2ea7
Create Date: 2026-02-11 18:36:53.187300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae3abb66486'
down_revision = '60c5034e2ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=500), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('unique_active_item_code', postgresql_where='((is_deleted = false) AND (item_code IS NOT NULL))')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('unique_active_item_code', ['item_code'], unique=True, postgresql_where='((is_deleted = false) AND (item_code IS NOT NULL))')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
