"""Add address_id to shippings table

Revision ID: 2b85760e9d14
Revises: ff106ad31655
Create Date: 2026-01-19 23:26:04.117712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b85760e9d14'
down_revision = 'ff106ad31655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['address_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
