"""drop_quotation_coloum

Revision ID: 3077b3d2a098
Revises: d1d88999523f
Create Date: 2026-01-15 19:31:56.447491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3077b3d2a098'
down_revision = 'd1d88999523f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('terms_and_conditions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_and_conditions', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
