"""Add name to ItemImage

Revision ID: 4a0357dfec4b
Revises: 86ac872a9d88
Create Date: 2026-03-10 15:32:08.990333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0357dfec4b'
down_revision = '86ac872a9d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
