"""Remove address_id from shippings table

Revision ID: 4b65c45c91ab
Revises: 4e0998921e02
Create Date: 2026-01-29 17:17:29.950857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b65c45c91ab'
down_revision = '9591d6a41942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shippings_address', type_='foreignkey')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_shippings_address', 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###
