"""Change address_type to ENUM

Revision ID: 4e0998921e02
Revises: a1b2c3d4e5f6
Create Date: 2026-01-29 16:18:59.085734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0998921e02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_entries',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entered_bill', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_column('shipping_id')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.Enum('home', 'work', 'other', name='shipping_address_type'), nullable=False))
        batch_op.create_index('one_default_shipping_per_customer', ['customer_id'], unique=True, postgresql_where=sa.text('is_default = true'))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_created_by_uuid_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_updated_by_uuid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_updated_by_uuid_fkey', 'users', ['updated_by'], ['uuid'])
        batch_op.create_foreign_key('users_created_by_uuid_fkey', 'users', ['created_by'], ['uuid'])

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('one_default_shipping_per_customer', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_column('address_type')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.UUID(), autoincrement=False, nullable=True))

    op.drop_table('purchase_entries')
    # ### end Alembic commands ###
