"""Add original_invoice_payment_status to debit_notes

Revision ID: 53d4a0b44143
Revises: 5e6186258f86
Create Date: 2026-03-18 21:51:16.686227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d4a0b44143'
down_revision = '5e6186258f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_invoice_payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_notes', schema=None) as batch_op:
        batch_op.drop_column('original_invoice_payment_status')

    # ### end Alembic commands ###
