"""Add shipping and customer address relationships

Revision ID: 569e8c5cd8f8
Revises: 1923cfb0ccbb
Create Date: 2026-01-23 12:24:32.169801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569e8c5cd8f8'
down_revision = '1923cfb0ccbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check if shippings table already exists
    shippings_check = conn.execute(sa.text("""
        SELECT COUNT(*) FROM information_schema.tables 
        WHERE table_name = 'shippings'
    """)).scalar()
    
    if shippings_check == 0:
        # Create shippings table
        op.create_table('shippings',
            sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
            sa.Column('customer_id', sa.UUID(), nullable=False),
            sa.Column('address_id', sa.UUID(), nullable=False),
            sa.Column('address1', sa.String(length=255), nullable=True),
            sa.Column('address2', sa.String(length=255), nullable=True),
            sa.Column('city', sa.String(length=100), nullable=True),
            sa.Column('state', sa.String(length=100), nullable=True),
            sa.Column('country', sa.String(length=100), nullable=True),
            sa.Column('pin', sa.String(length=20), nullable=True),
            sa.Column('business_id', sa.Integer(), nullable=True),
            sa.Column('created_by', sa.UUID(), nullable=True),
            sa.Column('updated_by', sa.UUID(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=True),
            sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], name='fk_shippings_address'),
            sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], name='fk_shippings_created_by'),
            sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], name='fk_shippings_customer'),
            sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], name='fk_shippings_updated_by'),
            sa.PrimaryKeyConstraint('uuid')
        )
        
        # Create indexes for shippings
        op.create_index('idx_shippings_customer_id', 'shippings', ['customer_id'], unique=False)
        op.create_index('idx_shippings_address_id', 'shippings', ['address_id'], unique=False)
    
    # Check if customer_addresses table already exists
    customer_addresses_check = conn.execute(sa.text("""
        SELECT COUNT(*) FROM information_schema.tables 
        WHERE table_name = 'customer_addresses'
    """)).scalar()
    
    if customer_addresses_check == 0:
        # Create customer_addresses table
        op.create_table('customer_addresses',
            sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
            sa.Column('customer_id', sa.UUID(), nullable=False),
            sa.Column('address_id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], name='fk_customer_addresses_address'),
            sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], name='fk_customer_addresses_customer'),
            sa.PrimaryKeyConstraint('uuid')
        )
    
    # Add customer_id to addresses table
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_addresses_customer', 'customers', ['customer_id'], ['uuid'])
    # ### end Alembic commands ###
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint from addresses
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_addresses_customer', type_='foreignkey')
        batch_op.drop_column('customer_id')
    # Drop customer_addresses table
    op.drop_table('customer_addresses')
    # Drop shippings table and its indexes
    op.drop_index('idx_shippings_address_id', table_name='shippings')
    op.drop_index('idx_shippings_customer_id', table_name='shippings')
    op.drop_table('shippings')
    
    # ### end Alembic commands ###