"""Remove lead_address_id from shippings table

Revision ID: 5bef810bed92
Revises: a8298da99cb7
Create Date: 2026-01-19 19:44:10.847969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bef810bed92'
down_revision = 'a8298da99cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        # First drop the foreign key constraint
        batch_op.drop_constraint('shippings_lead_address_id_fkey', type_='foreignkey')
        # Then drop the column
        batch_op.drop_column('lead_address_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_address_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('shippings_lead_address_id_fkey', 'lead_addresses', ['lead_address_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
