"""Removed unique item name from item module

Revision ID: 60c5034e2ea7
Revises: 455e701689e3
Create Date: 2026-02-09 21:27:55.149345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c5034e2ea7'
down_revision = '455e701689e3','a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_item_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint('items_item_name_key', ['item_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
