"""add addresses

Revision ID: 625bb531c61b
Revises: a4ec610b1e54
Create Date: 2025-08-26 16:38:09.250505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625bb531c61b'
down_revision = 'a4ec610b1e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Changes already applied to the database manually or by previous run
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('business_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
