"""Shipping table added relationship with the customer and address table

Revision ID: 655b587305b9
Revises: b18a842d5e10
Create Date: 2026-01-19 17:22:06.405301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655b587305b9'
down_revision = 'b18a842d5e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_mobile_key', type_='unique')
        batch_op.create_unique_constraint('uq_customers_lead_id', ['lead_id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('leads_mobile_key', type_='unique')

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('address_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('lead_address_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))
        batch_op.create_index('one_default_shipping_per_customer', ['customer_id'], unique=True, postgresql_where=sa.text('is_default = true'))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'lead_addresses', ['lead_address_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('one_default_shipping_per_customer', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_column('is_default')
        batch_op.drop_column('lead_address_id')
        batch_op.drop_column('address_id')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_unique_constraint('leads_mobile_key', ['mobile'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_lead_id', type_='unique')
        batch_op.create_unique_constraint('customers_mobile_key', ['mobile'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
