"""fix the nullable value

Revision ID: 78378e556695
Revises: ed2ef03bf966
Create Date: 2026-01-02 19:28:19.756777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78378e556695'
down_revision = 'ed2ef03bf966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('person_addresses')
    # op.drop_table('persons')
    # op.drop_table('person_types')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.drop_constraint('leads_mobile_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_unique_constraint('leads_mobile_key', ['mobile'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # op.create_table('person_types',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('person_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='person_types_business_id_fkey', ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='person_types_created_by_fkey', ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='person_types_updated_by_fkey', ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id', name='person_types_pkey'),
    # sa.UniqueConstraint('name', name='person_types_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('persons',
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('person_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('gst', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    # sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    # sa.Column('referenced_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    # sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='persons_created_by_fkey', ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['person_type_id'], ['person_types.id'], name='persons_person_type_id_fkey', ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='persons_updated_by_fkey', ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('uuid', name='persons_pkey'),
    # sa.UniqueConstraint('mobile', name='persons_mobile_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('person_addresses',
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], name='person_addresses_address_id_fkey', ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='person_addresses_created_by_fkey', ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['person_id'], ['persons.uuid'], name='person_addresses_person_id_fkey', ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='person_addresses_updated_by_fkey', ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('uuid', name='person_addresses_pkey')
    # )
    # ### end Alembic commands ###
