"""Added the ids deleted column

Revision ID: 800a4255e920
Revises: 8dfd9591067d
Create Date: 2026-02-27 22:41:21.498944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800a4255e920'
down_revision = '8dfd9591067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))

    # Update existing records to set default value
    op.execute("UPDATE invoices SET is_deleted = false WHERE is_deleted IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', nullable=False)

    # Skip PostgreSQL-specific index operations for SQLite
    # SQLite doesn't support partial indexes with WHERE clauses like PostgreSQL
    # These indexes will be handled differently or may not be needed for SQLite

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip PostgreSQL-specific index recreation for SQLite
    
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
