"""Added mobileNo

Revision ID: 81a0ee186ca0
Revises: 0b13cae3b3c7
Create Date: 2025-09-12 16:37:04.337286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a0ee186ca0'
down_revision = '0b13cae3b3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Helper function to safely add columns
    def safe_add_column(table_name, column_name, column_definition):
        conn = op.get_bind()
        result = conn.execute(sa.text(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = '{table_name}' AND column_name = '{column_name}'
        """))
        if not result.fetchone():
            with op.batch_alter_table(table_name, schema=None) as batch_op:
                batch_op.add_column(column_definition)
                return True
        return False
    
    # Add mobileNo column only if it doesn't exist
    if safe_add_column('users', 'mobileNo', sa.Column('mobileNo', sa.String(length=10), nullable=True)):
        # Only create constraint if column was actually added
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_unique_constraint(None, ['mobileNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mobileNo')

    # ### end Alembic commands ###
