# """add table quotation

# Revision ID: 84023d37756f
# Revises: 6daa1d1dd9b9
# Create Date: 2026-01-15 18:44:56.824648

# """
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84023d37756f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    pass

def downgrade():
    pass


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('person_types')
#     op.drop_table('shippings')
#     op.drop_table('persons')
#     op.drop_table('person_addresses')
#     with op.batch_alter_table('addresses', schema=None) as batch_op:
#         batch_op.alter_column('business_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)

#     with op.batch_alter_table('customers', schema=None) as batch_op:
#         batch_op.drop_constraint('customers_mobile_key', type_='unique')
#         batch_op.create_unique_constraint('uq_customers_lead_id', ['lead_id'])

#     with op.batch_alter_table('items', schema=None) as batch_op:
#         batch_op.drop_constraint('fk_items_category', type_='foreignkey')

#     with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
#         batch_op.drop_constraint('lead_addresses_shipping_id_fkey', type_='foreignkey')
#         batch_op.drop_column('shipping_id')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('shipping_id', sa.UUID(), autoincrement=False, nullable=True))
#         batch_op.create_foreign_key('lead_addresses_shipping_id_fkey', 'shippings', ['shipping_id'], ['uuid'], ondelete='CASCADE')

#     with op.batch_alter_table('items', schema=None) as batch_op:
#         batch_op.create_foreign_key('fk_items_category', 'item_categories', ['category_id'], ['uuid'], ondelete='SET NULL')

#     with op.batch_alter_table('customers', schema=None) as batch_op:
#         batch_op.drop_constraint('uq_customers_lead_id', type_='unique')
#         batch_op.create_unique_constraint('customers_mobile_key', ['mobile'], postgresql_nulls_not_distinct=False)

#     with op.batch_alter_table('addresses', schema=None) as batch_op:
#         batch_op.alter_column('business_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)

#     op.create_table('person_addresses',
#     sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], name='person_addresses_address_id_fkey', ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='person_addresses_created_by_fkey', ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['person_id'], ['persons.uuid'], name='person_addresses_person_id_fkey', ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='person_addresses_updated_by_fkey', ondelete='SET NULL'),
#     sa.PrimaryKeyConstraint('uuid', name='person_addresses_pkey')
#     )
#     op.create_table('persons',
#     sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('person_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
#     sa.Column('gst', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
#     sa.Column('referenced_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='persons_created_by_fkey', ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['person_type_id'], ['person_types.id'], name='persons_person_type_id_fkey', ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='persons_updated_by_fkey', ondelete='SET NULL'),
#     sa.PrimaryKeyConstraint('uuid', name='persons_pkey'),
#     sa.UniqueConstraint('mobile', name='persons_mobile_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
#     )
#     op.create_table('shippings',
#     sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('address1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
#     sa.Column('address2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
#     sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('pin', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
#     sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='shippings_business_id_fkey', ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='shippings_created_by_fkey', ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='shippings_updated_by_fkey', ondelete='SET NULL'),
#     sa.PrimaryKeyConstraint('uuid', name='shippings_pkey')
#     )
#     op.create_table('person_types',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
#     sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='person_types_business_id_fkey', ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='person_types_created_by_fkey', ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='person_types_updated_by_fkey', ondelete='SET NULL'),
#     sa.PrimaryKeyConstraint('id', name='person_types_pkey'),
#     sa.UniqueConstraint('name', name='person_types_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
#     )
#     # ### end Alembic commands ###
