"""Add is_main to ItemImage

Revision ID: 86ac872a9d88
Revises: 20a7dd1f1a10
Create Date: 2026-03-10 14:46:24.588303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ac872a9d88'
down_revision = '20a7dd1f1a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###
