"""add_purchase_orders_and_purchase_order_items_tables

Revision ID: 89bb74cac7b9
Revises: b1e2f3a4c5d6
Create Date: 2026-03-10 17:54:00.192960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bb74cac7b9'
down_revision = 'b1e2f3a4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('additional_notes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('po_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('idx_purchase_orders_business_id', ['business_id'], unique=False)
        batch_op.create_index('idx_purchase_orders_business_status_delivery', ['business_id', 'status', 'delivery_date'], unique=False)
        batch_op.create_index('idx_purchase_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_purchase_orders_status', ['status'], unique=False)
        batch_op.create_index('idx_purchase_orders_status_delivery_date', ['status', 'delivery_date'], unique=False)
        batch_op.create_index('idx_purchase_orders_vendor_id', ['vendor_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.JSON(), nullable=True),
    sa.Column('tax', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index('idx_purchase_order_items_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_purchase_order_items_po_id', ['purchase_order_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('idx_customers_fullname_trgm', postgresql_ops={"lower((first_name::text || ' '::text) || last_name::text)": 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(is_deleted = false)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customers_fullname_trgm', [sa.text("lower((first_name::text || ' '::text) || last_name::text)")], unique=False, postgresql_ops={"lower((first_name::text || ' '::text) || last_name::text)": 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(is_deleted = false)')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_purchase_order_items_po_id')
        batch_op.drop_index('idx_purchase_order_items_item_id')

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('idx_purchase_orders_vendor_id')
        batch_op.drop_index('idx_purchase_orders_status_delivery_date')
        batch_op.drop_index('idx_purchase_orders_status')
        batch_op.drop_index('idx_purchase_orders_created_at')
        batch_op.drop_index('idx_purchase_orders_business_status_delivery')
        batch_op.drop_index('idx_purchase_orders_business_id')

    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
