"""Remove or comment out this line

Revision ID: 8c91db2f51c1
Revises: b69397ae2a66
Create Date: 2025-09-30 15:22:38.783547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c91db2f51c1'
down_revision = 'b69397ae2a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('address_type')

    # NOTE: Do NOT enforce NOT NULL on customers.lead_id here because
    # existing data may contain NULLs. We'll backfill and enforce in a later migration.
    # with op.batch_alter_table('customers', schema=None) as batch_op:
    #     batch_op.alter_column('lead_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_column('address_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
