"""added country & UnionTerritory table

Revision ID: 99bf63f925e2
Revises: 234dafe8acf5
Create Date: 2026-02-23 16:04:25.476098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bf63f925e2'
down_revision = '234dafe8acf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('country_name', sa.String(length=150), nullable=False),
    sa.Column('iso_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('union_territories',
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('territory_name', sa.String(length=150), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('territory_type', sa.String(length=100), nullable=False),
    sa.Column('capital', sa.String(length=150), nullable=True),
    sa.Column('is_capital_territory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('territory_id'),
    sa.UniqueConstraint('territory_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('union_territories')
    op.drop_table('countries')
    # ### end Alembic commands ###
