"""adding basemixin for user

Revision ID: 9a8b8dbf250b
Revises: 754074390f48
Create Date: 2026-01-27 17:09:12.184137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8b8dbf250b'
down_revision = '754074390f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_addresses_customer', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'shippings', ['shipping_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('user_business', schema=None) as batch_op:
        batch_op.drop_constraint('user_business_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['uuid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.UUID(), nullable=True))
        batch_op.drop_constraint('fk_users_updated_by_uuid', type_='foreignkey')
        batch_op.drop_constraint('fk_users_created_by_uuid', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.drop_column('updated_by_uuid')
        batch_op.drop_column('created_by_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_uuid', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_by_uuid', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_users_created_by_uuid', 'users', ['created_by_uuid'], ['uuid'])
        batch_op.create_foreign_key('fk_users_updated_by_uuid', 'users', ['updated_by_uuid'], ['uuid'])
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('user_business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_business_user_id_fkey', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipping_id')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_addresses_customer', 'customers', ['customer_id'], ['uuid'], ondelete='SET NULL')

    # ### end Alembic commands ###
