"""Update shipping address handling

Revision ID: 9b277e689adc
Revises: 2b85760e9d14
Create Date: 2026-01-20 16:51:56.413272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b277e689adc'
down_revision = '2b85760e9d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint('shippings_address_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.create_unique_constraint('shippings_address_id_key', ['address_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
