"""Active-type add id

Revision ID: a4ec610b1e54
Revises: 7a101c356b7d
Create Date: 2025-08-25 19:41:47.649114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ec610b1e54'
down_revision = '5dc35df03744'
branch_labels = None
depends_on = None


def upgrade():
    # Changes already applied to the database manually or by previous run
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('active_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('active', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('active_active_type_uuid_fkey', 'active_types', ['active_type_uuid'], ['uuid'], ondelete='SET NULL')
        batch_op.alter_column('active_type_uuid',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###
