"""added isdeted colum

Revision ID: a5f1bc098193
Revises: 1282b813c7d0
Create Date: 2026-02-09 16:44:10.395189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5f1bc098193'
down_revision = '1282b813c7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    op.create_table('invoices',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quotation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('balance_due', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('charges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('additional_notes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='invoices_business_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], name='invoices_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], name='invoices_customer_id_fkey'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.uuid'], name='invoices_quotation_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], name='invoices_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid', name='invoices_pkey'),
    sa.UniqueConstraint('invoice_number', name='invoices_invoice_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('invoice_items',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tax', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], name='invoice_items_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.uuid'], name='invoice_items_invoice_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='invoice_items_item_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], name='invoice_items_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid', name='invoice_items_pkey')
    )
    # ### end Alembic commands ###
