"""Remove or comment out this line

Revision ID: a81ba10a12d9
Revises: 0ec21941a859
Create Date: 2025-09-30 15:18:08.377970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81ba10a12d9'
down_revision = '0ec21941a859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
