"""Made the customer relationship with the addresses table

Revision ID: a8298da99cb7
Revises: c3a67579c9d7
Create Date: 2026-01-19 19:38:20.067540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8298da99cb7'
down_revision = 'c3a67579c9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'address_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
