"""add_address_type_to_shippings

Revision ID: add_address_type_to_shippings
Revises: 96eb6b871daf
Create Date: 2026-02-02 21:56:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_address_type_to_shippings'
down_revision = '96eb6b871daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the ENUM type if it doesn't exist
    address_type_enum = sa.Enum('home', 'work', 'other', name='shipping_address_type')
    address_type_enum.create(op.get_bind())
    
    # Add address_type column to shippings table
    op.add_column('shippings', sa.Column('address_type', address_type_enum, nullable=False, server_default='home'))
    
    # Create index for unique default shipping per customer
    op.create_index('one_default_shipping_per_customer', 'shippings', ['customer_id'], 
                   unique=True, postgresql_where=sa.text('is_default = true'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the index first
    op.drop_index('one_default_shipping_per_customer', table_name='shippings', 
                  postgresql_where=sa.text('is_default = true'))
    
    # Drop the column
    op.drop_column('shippings', 'address_type')
    
    # Drop the ENUM type
    op.execute("DROP TYPE IF EXISTS shipping_address_type")
    
    # ### end Alembic commands ###
