"""Add is_deleted column to PaymentIn and PaymentOut tables

Revision ID: add_is_deleted_to_payment_tables
Revises: 
Create Date: 2026-04-06 19:46:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'add_is_deleted_to_payment_tables'
down_revision = '0217ed50fba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add is_deleted column to PaymentIn table
    op.add_column('payment_ins', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Add is_deleted column to PaymentOut table
    op.add_column('payment_outs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove is_deleted column from PaymentIn table
    op.drop_column('payment_ins', 'is_deleted')
    
    # Remove is_deleted column from PaymentOut table
    op.drop_column('payment_outs', 'is_deleted')
