"""Remove or comment out this line

Revision ID: b69397ae2a66
Revises: a81ba10a12d9
Create Date: 2025-09-30 15:19:48.628889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69397ae2a66'
down_revision = 'a81ba10a12d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('address_type')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_column('address_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check and add address_type to shippings if it doesn't exist
    if 'shippings' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('shippings')]
        if 'address_type' not in columns:
            with op.batch_alter_table('shippings', schema=None) as batch_op:
                batch_op.add_column(sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=True))
                # First add as nullable, then update all rows, then set to NOT NULL
                op.execute("UPDATE shippings SET address_type = 0 WHERE address_type IS NULL")
                batch_op.alter_column('address_type', nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Check and add address_type to addresses if it doesn't exist
    if 'addresses' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('addresses')]
        if 'address_type' not in columns:
            with op.batch_alter_table('addresses', schema=None) as batch_op:
                batch_op.add_column(sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=True))
                # First add as nullable, then update all rows, then set to NOT NULL
                op.execute("UPDATE addresses SET address_type = 0 WHERE address_type IS NULL")
                batch_op.alter_column('address_type', nullable=False)

    # ### end Alembic commands ###
