"""add purchase invoices

Revision ID: b9c0801a0c60
Revises: 89bb74cac7b9
Create Date: 2026-03-12 19:45:18.231765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c0801a0c60'
down_revision = '89bb74cac7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_invoices',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('inventory_updated', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('additional_notes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('purchase_invoice_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('purchase_invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.JSON(), nullable=True),
    sa.Column('tax', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_invoice_items')
    op.drop_table('purchase_invoices')
    # ### end Alembic commands ###
