"""Rename column path to value

Revision ID: c1d2ec8c748e
Revises: d706fa549659
Create Date: 2026-03-16 16:03:02.746813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2ec8c748e'
down_revision = 'd706fa549659','e0a913a62a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_config', schema=None) as batch_op:
        batch_op.alter_column('path', new_column_name='value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_config', schema=None) as batch_op:
        batch_op.alter_column('value', new_column_name='path')

    # ### end Alembic commands ###
