"""Removed the lead_address_id_column

Revision ID: c3a67579c9d7
Revises: 0b92b47c6988
Create Date: 2026-01-19 18:29:37.133608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a67579c9d7'
down_revision = '0b92b47c6988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.drop_constraint('shippings_lead_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('lead_address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_address_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('shippings_lead_address_id_fkey', 'lead_addresses', ['lead_address_id'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###
