"""Reset migration history to clean state
 
Revision ID: c3d4e5f6g7h8
Revises: 3e7143562dbb
Create Date: 2026-02-10 20:50:00.000000
 
"""
from alembic import op
import sqlalchemy as sa
 
 
# revision identifiers, used by Alembic.
revision = 'c3d4e5f6g7h8'
down_revision = '3e7143562dbb'
branch_labels = None
depends_on = None
 
 
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    # Add missing customer_id to addresses table
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_addresses_customer_id', 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')
 
    # Add missing is_deleted columns
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default=sa.text('false')))
 
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default=sa.text('false')))
 
    # Add missing referenced_by column to leads
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenced_by', sa.String(length=120), nullable=True))
 
    # Add shipping table
    op.create_table('shippings',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.Enum('home', 'work', 'other', name='shipping_address_type'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pin', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.Index('one_default_shipping_per_customer', 'customer_id', unique=True, postgresql_where=sa.text('is_default = true'))
    )
 
    # Fix user audit column names in addresses table
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_addresses_created_by', 'users', ['created_by'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_addresses_updated_by', 'users', ['updated_by'], ['uuid'], ondelete='SET NULL')
 
    # Create invoices table
    op.create_table('invoices',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charges', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('additional_notes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('invoice_number')
    )
 
    # Create invoice_items table
    op.create_table('invoice_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.JSON(), nullable=True),
    sa.Column('tax', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
 
    # Update quotations table to match current models
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        # Only add if not exists
        batch_op.add_column(sa.Column('quotation_number', sa.String(length=50), nullable=False, server_default=sa.text('')))
        batch_op.add_column(sa.Column('charges', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint('uq_quotations_quotation_number', ['quotation_number'])
 
        # Drop old columns if they exist
        try:
            batch_op.drop_column('discount_total')
        except:
            pass
        try:
            batch_op.drop_column('subtotal')
        except:
            pass
        try:
            batch_op.drop_column('billing_address_id')
        except:
            pass
        try:
            batch_op.drop_column('tax_total')
        except:
            pass
        try:
            batch_op.drop_column('shipping_address_id')
        except:
            pass
        try:
            batch_op.drop_column('additional_charges_total')
        except:
            pass
        try:
            batch_op.drop_column('round_off')
        except:
            pass
 
    # ### end Alembic commands ###
 
 
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    op.drop_table('shippings')
 
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
 
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('referenced_by')
        batch_op.drop_column('is_deleted')
 
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_addresses_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_addresses_created_by', type_='foreignkey')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_constraint('fk_addresses_customer_id', type_='foreignkey')
        batch_op.drop_column('customer_id')
    # ### end Alembic commands ###