"""Change item_images.image column from bytea to text

Revision ID: c590c3437f0a
Revises: c1d2ec8c748e
Create Date: 2026-03-18 19:52:31.204347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c590c3437f0a'
down_revision = 'c1d2ec8c748e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_credit_note_items_credit_note')
        batch_op.drop_index('idx_credit_note_items_item')

    with op.batch_alter_table('credit_note_payments', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_credit_note_payments_credit_note')
        batch_op.drop_index('idx_credit_note_payments_date')
        batch_op.drop_index('idx_credit_note_payments_deleted')
        batch_op.drop_index('idx_credit_note_payments_status')

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_credit_notes_business')
        batch_op.drop_index('idx_credit_notes_customer')
        batch_op.drop_index('idx_credit_notes_date')
        batch_op.drop_index('idx_credit_notes_deleted')
        batch_op.drop_index('idx_credit_notes_invoice')
        batch_op.drop_index('idx_credit_notes_number')
        batch_op.drop_index('idx_credit_notes_status')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index('idx_invoices_status')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('payment_ins', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_payment_ins_business_id')
        batch_op.drop_index('idx_payment_ins_created_by')
        batch_op.drop_index('idx_payment_ins_invoice_id')
        batch_op.drop_index('idx_payment_ins_payment_date')
        batch_op.drop_index('idx_payment_ins_updated_by')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.create_index('idx_quotation_items_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_quotation_items_quotation_id', ['quotation_id'], unique=False)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('idx_quotations_business_id', ['business_id'], unique=False)
        batch_op.create_index('idx_quotations_business_status_valid_till', ['business_id', 'status', 'valid_till'], unique=False)
        batch_op.create_index('idx_quotations_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_quotations_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_quotations_status', ['status'], unique=False)
        batch_op.create_index('idx_quotations_status_valid_till', ['status', 'valid_till'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('idx_quotations_status_valid_till')
        batch_op.drop_index('idx_quotations_status')
        batch_op.drop_index('idx_quotations_customer_id')
        batch_op.drop_index('idx_quotations_created_at')
        batch_op.drop_index('idx_quotations_business_status_valid_till')
        batch_op.drop_index('idx_quotations_business_id')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_index('idx_quotation_items_quotation_id')
        batch_op.drop_index('idx_quotation_items_item_id')

    with op.batch_alter_table('payment_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.create_index('idx_payment_ins_updated_by', ['updated_by'], unique=False)
        batch_op.create_index('idx_payment_ins_payment_date', ['payment_date'], unique=False)
        batch_op.create_index('idx_payment_ins_invoice_id', ['invoice_id'], unique=False)
        batch_op.create_index('idx_payment_ins_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_payment_ins_business_id', ['business_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('idx_invoices_status', ['status'], unique=False)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index('idx_credit_notes_status', ['status'], unique=False)
        batch_op.create_index('idx_credit_notes_number', ['credit_note_number'], unique=False)
        batch_op.create_index('idx_credit_notes_invoice', ['invoice_id'], unique=False)
        batch_op.create_index('idx_credit_notes_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('idx_credit_notes_date', ['credit_note_date'], unique=False)
        batch_op.create_index('idx_credit_notes_customer', ['customer_id'], unique=False)
        batch_op.create_index('idx_credit_notes_business', ['business_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('credit_note_payments', schema=None) as batch_op:
        batch_op.create_index('idx_credit_note_payments_status', ['status'], unique=False)
        batch_op.create_index('idx_credit_note_payments_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('idx_credit_note_payments_date', ['payment_date'], unique=False)
        batch_op.create_index('idx_credit_note_payments_credit_note', ['credit_note_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('invoice_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('credit_note_items', schema=None) as batch_op:
        batch_op.create_index('idx_credit_note_items_item', ['item_id'], unique=False)
        batch_op.create_index('idx_credit_note_items_credit_note', ['credit_note_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
