"""Create_quotation_tables

Revision ID: d1d88999523f
Revises: ffa8428faf16
Create Date: 2026-01-15 19:27:28.705809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d88999523f'
down_revision = 'ffa8428faf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('billing_address_id', sa.UUID(), nullable=False),
    sa.Column('shipping_address_id', sa.UUID(), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('additional_charges_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['addresses.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.uuid'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('quotation_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('measuring_unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_before_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['measuring_unit_id'], ['measuring_units.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_items')
    op.drop_table('quotations')
    # ### end Alembic commands ###
