"""Add reason column to Customer table

Revision ID: d1f711b5e4f2
Revises: a5f1bc098193
Create Date: 2026-02-10 20:46:13.040302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f711b5e4f2'
down_revision = 'a5f1bc098193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
