"""Make item optional fields nullable for module 1

Revision ID: ed2ef03bf966
Revises: 8c91db2f51c1
Create Date: 2025-12-17 19:38:05.579402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2ef03bf966'
down_revision = '8c91db2f51c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, set default values for any NULL values in the columns we're making NOT NULL
    op.execute("UPDATE items SET purchase_price = 0 WHERE purchase_price IS NULL")
    op.execute("UPDATE items SET item_code = '' WHERE item_code IS NULL")
    
    # Now alter the columns to be NOT NULL
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
