"""adding soft deleted

Revision ID: f0e3fcaa1238
Revises: 8d462b05adae
Create Date: 2026-01-30 22:08:53.376186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e3fcaa1238'
down_revision = '8d462b05adae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
