"""Added_quotation_table

Revision ID: ffa8428faf16
Revises: 7a101c356b7d
Create Date: 2026-01-15 19:23:05.879290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa8428faf16'
down_revision = '7a101c356b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_mobile_key', type_='unique')
        batch_op.create_unique_constraint('uq_customers_lead_id', ['lead_id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_category', type_='foreignkey')

    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.drop_column('shipping_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.UUID(), autoincrement=False, nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_items_category', 'item_categories', ['category_id'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_lead_id', type_='unique')
        batch_op.create_unique_constraint('customers_mobile_key', ['mobile'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
